### ISSUE TITLE
Smooth scrolling not working

### ISSUE THREAD

**Issue by Susensio** [Dedas/linux-scroll-speed-fix#1]
I don't know if this is an expected behaviour.
By default (without this extension) Chrome smooths scroll and this is easier on the eyes.
With this extension, scrolling becomes too instantaneous and not smooth at all.

**Comment by Dedas** [comment]
I will look into it but I'm unsure if it can be emulated.

**Comment by Dedas** [comment]
Smooth scrolling is not supported by this extension as of now. This might change if Google decides to properly support it in the Linux version of Chrome.
