### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by WittyNameHere** [Dedas/linux-scroll-speed-fix#3]
(Edited for etiquette and clarity)

I've seen it stated several times the smooth scrolling checkbox was defunct due to a lack of HW acceleration. Chrome for Linux added hardware acceleration in v86. Hardware-accelerated video decoding is now included (enabled in chrome:flags) in v88. It seems to work with my Nvidia hardware, and Nvidia is usually picky on Linux.

Can the checkbox for smooth scrolling please be workable? I get that to you the author the experience may be sub-par, but it's a sub-par experience that I personally prefer.

**Comment by Dedas** [comment]
Click customize speed and it will enable the option.

**Comment by WittyNameHere** [comment]
It still feels 'choppier' than it is without the extension running, but maybe that's things moving 90% faster. Thanks.
