### ISSUE TITLE
Any chance for smoother scrolling?

### ISSUE THREAD

**Issue by coxackie** [Dedas/linux-scroll-speed-fix#4]
As others have mentioned, scrolling in Linux is fast with this extension, but it is also very choppy. Is there any way the situation can be improved?

**Comment by Dedas** [comment]
I will look into it but no promises.

**Comment by coxackie** [comment]
Of course. We will appreciate any improvement. At least now that hardware acceleration is there in the Linux chromium builds. Keeping fingers crossed. Many thanks!

**Comment by hossain666** [comment]
mijorus:ignore-domains
