### ISSUE TITLE
Broken scrolling on Nexus Mods

### ISSUE THREAD

**Issue by WesCook** [Dedas/linux-scroll-speed-fix#5]
With this extension installed, scrolling isn't functional on [Nexus Mods](https://www.nexusmods.com/).

Disabling `overflow-x: hidden` on the body, or disabling `height: 100%` on both body and html elements seems to fix the issue.  Copying these properties to another page doesn't replicate the problem though, so there's something else going on.

**Comment by Dedas** [comment]
Thank you for reporting! I think I tracked it down. Will test to se if the fix affects other elements negatively.

**Comment by WesCook** [comment]
I found another example, if you'd like to test your fix.

https://www.appbrain.com/app/chrono-trigger-upgrade-ver/com.square_enix.android_googleplay.chrono

This page also applies `height: 100%` to html and body, and sets an overflow property on the body.

**Comment by Dedas** [comment]
Issue should be resolved in version 1.6.6. Please confirm.

**Comment by WesCook** [comment]
Looks like it works here.  The two examples above are scrolling as expected.  Thanks for the fix!
