### ISSUE TITLE
Wheel scrolling broken on outlook web app

### ISSUE THREAD

**Issue by coxackie** [Dedas/linux-scroll-speed-fix#6]
I am on Arch linux, using chromium as a browser, and I have a weird bug. I am using the outlook web app (https://outlook.office365.com/) and with the extension enabled wheel scrolling does not work in the view pane of the email. It works ok to scroll through the messages on the left pane, but once one email is selected and appears on the right pane, then if it cannot fit on the pane and scrollbars appear, wheel scrolling does not work. If I disable the extension, everything is OK.

I do not know what other info to give, or whether the above description is understandable, but let me know if you need any further info.

Edit: The issue only started lately. I cannot know for sure when exactly I noticed it, but it may be related to the latest versions in June. I thought it is something wrong with the browser update, and only today I checked whether the extension may be responsible.

**Comment by faea726** [comment]
All web with tile/docked bar has problem. Images bellow are example.
![2021-08-29_17-32-35](https://user-images.githubusercontent.com/37011495/131247308-1372726e-e8f5-472d-9ba6-d3426dd25bd5.png)
![2021-08-29_17-33-46](https://user-images.githubusercontent.com/37011495/131247338-b478c96f-cb03-4873-8cae-ac520af04c23.png)

**Comment by coxackie** [comment]
@faea726 I don't think this is the same issue - the problem in outlook website is that scrolling does not work at all. I can, however, confirm the issue you are facing - I also noticed it. Maybe worthwhile opening a separate ticket for that. For the time being I have switch to the SmoothScroll extension (which, surprisingly, also offers smoother scrolling), waiting for the issues here to be ironed out.

**Comment by Dedas** [comment]
> All web with tile/docked bar has problem. Images bellow are example.
> ![2021-08-29_17-32-35](https://user-images.githubusercontent.com/37011495/131247308-1372726e-e8f5-472d-9ba6-d3426dd25bd5.png)
> ![2021-08-29_17-33-46](https://user-images.githubusercontent.com/37011495/131247338-b478c96f-cb03-4873-8cae-ac520af04c23.png)

This error should be gone in 1.7.0.

**Comment by Dedas** [comment]
As a temporary measure I'm disabling scrolling modification in Outlook until a fix is found. That site does some really funky stuff messing up the calculations. I will need some more time to get a proper fix in place.

**Comment by Dedas** [comment]
Alright, I've seemed to have fixed it. Will publish 1.7.2.
