### ISSUE TITLE
Content from sites like Instagram won't load with the extension enabled

### ISSUE THREAD

**Issue by Salvaju29ro** [Dedas/linux-scroll-speed-fix#7]
Hi, I noticed that when the extension is active and I scroll down on instagram the photos load endlessly.
To load them I have to click on one of the photos and then they will load.
I tried to disable the extension and the problem is not there, so it may be that the problem is the extension itself

![Instagram](https://user-images.githubusercontent.com/10899871/130502351-56e790da-bc35-4499-a391-f1c98a16c61d.png)

**Comment by Dedas** [comment]
Issue is resolved in v1.7.0.
